### ISSUE TITLE
Enemies

### ISSUE THREAD

**Issue by AineeJames** [AineeJames/ToBeNamed#1]
- [x] Make nav not bounce
- [x] Make nav not get stuck on player
- [x] More enemy types

**Comment by wilcockj** [comment]
https://docs.godotengine.org/en/stable/tutorials/scripting/resources.html

resources could be a great way to define all the different enemies
make a resource that has texture, health, movement speed, etc. 
and then simply make a new resource for each enemy
```
extends Resource
class_name EnemyResource

export var texture: Texture
export var health: int
```

**Comment by AineeJames** [comment]
singletons (autoloads) could also be used for global game state / enemy information

Docs: https://docs.godotengine.org/en/stable/tutorials/scripting/singletons_autoload.html
![image](https://github.com/AineeJames/ToBeNamed/assets/71784728/05523173-2317-4710-a2b9-15c2cc46c73a)

**Comment by wilcockj** [comment]
#15 
Pull request I merged to have enemies loaded with a resource

**Comment by wilcockj** [comment]
#16 
Pull request to add lobbyist enemy and fix for health bar for different sprite sizes

**Comment by wilcockj** [comment]
#25 
added enemy attack radius cooldown and power

**Comment by wilcockj** [comment]
ermmm its ackshully good now
