### ISSUE TITLE
Fix Tileset

### ISSUE THREAD

**Issue by AineeJames** [AineeJames/ToBeNamed#26]

**Comment by wilcockj** [comment]
a1e6343264f40e14bcf7bef637bbc55c93392b63 fixed the issue

by clicking in the tileset the 3 dots and then 
![image](https://github.com/AineeJames/ToBeNamed/assets/33857120/6a66f0c7-1bf0-41ea-9101-e2c20cce3d38)
remove  tiles outside texture
